name: screenshot designated hotels landing page
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check_designated_hotel_screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: send screenshot of https://www.coronavirus.gov.hk/eng/designated-hotel-list.html
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          npm install --global capture-website-cli
          capture-website "https://www.coronavirus.gov.hk/eng/designated-hotel-list.html" --output=designated_hotels_list_screenshot.png --height=1600
          curl -F document=@designated_hotels_list_screenshot.png "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID}"
